[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "modular-composer"
description = "OtoKotoba Modular Composer"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Harusan", email = "haru@example.com" },
]
keywords = ["music", "midi", "generation", "plugin"]
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dynamic = ["version"]
dependencies = [
  "music21>=9.0",
  "PyYAML>=6.0",
  "pydantic>=2.7",
  "pydub>=0.25",
  "mido>=1.3.0",
  "tomli>=2.0",
  "audioread>=2.1.9",
  "pretty_midi>=0.2",
]

[project.optional-dependencies]
dev = ["pytest", "mypy", "ruff"]
test = [
  "music21>=9.1",
  "scikit-learn>=1.3.0",
  "librosa>=0.10.0",
  "soundfile>=0.12.0",
  "scipy>=1.10",
  "pretty_midi>=0.2.10",
  "mido",
  "python-rtmidi",
  "hdbscan>=0.8",
]
audio = [
  "librosa>=0.10",
  "soundfile>=0.12",
  "fluidsynth",
  "tqdm",
]
velocity = [
  "numpy>=1.24",
  "scipy>=1.10",
]
essentia = [
  "essentia>=2.1",
]
groove = [
  "pretty_midi>=0.2.10",
  "librosa>=0.10",
]
gui = ["streamlit", "plotly"]
rnn = ["torch==2.3.0", "pytorch_lightning==2.2.4", "optuna==3.6.1"]
live = ["mido>=1.3", "python-rtmidi>=1.5"]
ai = [
  "transformers>=4.43",
  "accelerate",
  "sentencepiece",
  "music21>=9.1",
  "pretty_midi>=0.2.10",
  "mido",
  "python-rtmidi",
  "hdbscan>=0.8",
]
data_ops = ["hmmlearn>=0.3"]
plugin = [
  "pybind11>=2.10",
  "cmake",
  "ninja",
]

all = [
  "pytest",
  "mypy",
  "ruff",
  "librosa>=0.10",
  "soundfile>=0.12",
  "fluidsynth",
  "tqdm",
  "numpy>=1.24",
  "scipy>=1.10",
  "essentia>=2.1",
  "pretty_midi>=0.2.10",
  "music21>=9.1",
  "mido",
  "python-rtmidi",
  "hdbscan>=0.8",
  "streamlit",
  "plotly",
  "torch==2.3.0",
  "pytorch_lightning==2.2.4",
  "optuna==3.6.1",
  "mido>=1.3",
  "python-rtmidi>=1.5",
  "transformers>=4.43",
  "accelerate",
  "sentencepiece",
  "hmmlearn>=0.3",
  "pybind11>=2.10",
  "cmake",
  "ninja",
]

[tool.hatch.version]
path = "modular_composer/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["modular_composer", "utilities"]

[project.scripts]
modcompose = "modular_composer.cli:main"

[tool.ruff]
target-version = "py310"
select = ["E", "F", "I", "UP"]
fix = true
line-length = 100
extend-exclude = [
    "generator/*",
    "utilities/*",
    "tests/*",
    "data/*",
    "Backup/*",
    "docs/*",
    "config/*",
    "midi_output/*",
    "scripts/*",
    "tools/*",
    "wheelhouse/*",
    "modular_composer.py",
    "emotion_humanizer.py",
    "groove_profile.py",
    "build_all_json.py",
    "run_generate_demo.sh",
    "setup.sh",
    "setup_project.sh",
    "streamlit_app/*",
]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["yaml"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["plotly.*", "streamlit.*", "sounddevice.*"]
ignore_missing_imports = true


[tool.pytest.ini_options]
markers = [
    "ci_perf: performance gate",
    "stretch: stretch smoke tests",
    "packaging: packaging checks",
    "docs: documentation build",
]
