[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "modular_composer"
version = "0.1.0"
description = "OtoKotoba Modular Composer"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name="Your Name", email="you@example.com" },
]
dependencies = [
  "music21>=9.6.0",
  "pretty_midi>=0.2.10",
  "numpy>=1.26.4,<2.0.0",
  "PyYAML>=6.0",
  "pydantic>=2.7",
  "pydub>=0.25",
  "mido>=1.3.0",
  "scipy>=1.10",
  "tomli>=2.0",
]
