[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "modular_composer"
version = "0.1.3"
description = "OtoKotoba Modular Composer"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name="Your Name", email="you@example.com" },
]
dependencies = [
  "music21>=9.6.0",
  "pretty_midi>=0.2.10",
  "numpy>=1.26.4,<2.0.0",
  "PyYAML>=6.0",
  "pydantic>=2.7",
  "pydub>=0.25",
  "mido>=1.3.0",
  "scipy>=1.10",
  "tomli>=2.0",
  "librosa>=0.10",
  "soundfile>=0.12",
  "audioread>=2.1.9"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "mypy",
  "ruff",
]
audio = [
  "librosa>=0.10",
  "soundfile>=0.12",
  "fluidsynth",
]

[project.scripts]
modcompose = "modular_composer.cli:main"

[tool.ruff]
target-version = "py310"
select = ["E", "F", "I", "UP"]
fix = true
line-length = 100
extend-exclude = [
    "generator/*",
    "utilities/*",
    "tests/*",
    "data/*",
    "Backup/*",
    "docs/*",
    "config/*",
    "midi_output/*",
    "scripts/*",
    "tools/*",
    "wheelhouse/*",
    "modular_composer.py",
    "emotion_humanizer.py",
    "groove_profile.py",
    "build_all_json.py",
    "run_generate_demo.sh",
    "setup.sh",
    "setup_project.sh",
]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = true

[tool.setuptools.packages.find]
include = ["modular_composer*", "utilities*"]
