# Default configuration for ML velocity training

input_dim: 3
batch_size: 8
epochs: 2
learning_rate: 0.001
num_workers: 0
data:
  train: tests/data/velocity_mini.csv
  val: tests/data/velocity_mini.csv
wandb: false
patience: 10
