# Default configuration for ML velocity training

input_dim: 3
batch_size: 8
learning_rate: 0.001
num_workers: 0
data:
  train: tests/data/velocity_mini.csv
  val: tests/data/velocity_mini.csv

trainer:
  max_epochs: 2
  accelerator: cpu
  gpus: null
  devices: null
  default_root_dir: ${hydra.run.dir}
  logger:
    use_wandb: false
  callbacks:
    early_stopping:
      patience: 10
      monitor: val_MSE
      mode: min
      stopping_threshold: 0.015
  checkpoint_path: checkpoints/last.ckpt
