name: Sax CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODC_BUILD_PLUGIN: OFF
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .[test]
      - name: Run tests
        run: make test
      - name: Generate demo MIDI
        run: make demo-sax
      - uses: actions/upload-artifact@v4
        with:
          name: demo-mid
          path: demos/*.mid
