name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Ruff
        run: ruff check . --output-format=github
      - name: Mypy
        run: mypy modular_composer utilities tests --strict
      - name: Pytest
        run: pytest -q --cov --cov-report=xml
      - name: Golden MIDI regression
        run: |
          files=$(ls tests/golden_midi/*.mid 2>/dev/null || true)
          if [ -z "$files" ]; then
            echo "no golden midi"
          else
            modcompose gm-test $files
          fi
      - name: Upload golden MIDI failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-failures
          path: tests/golden_midi/failed
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage.xml
