name: Groove Quick Test
on: [push, pull_request]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -e .[groove]
      - name: make loops
        run: |
          python - <<'PY'
          import pretty_midi, os
          os.makedirs('mini_loops', exist_ok=True)
          for i in range(2):
              pm = pretty_midi.PrettyMIDI(initial_tempo=120)
              inst = pretty_midi.Instrument(program=0, is_drum=True)
              inst.notes.append(pretty_midi.Note(velocity=100, pitch=36, start=0.0, end=0.1))
              pm.instruments.append(inst)
              pm.write(f'mini_loops/{i}.mid')
          PY
      - run: timeout 180 modcompose groove train mini_loops --order 2
