name: Groove Quick Test
on: [push, pull_request]

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        include:
          - env:
              PURE_PY: '1'
          - env:
              CYTHON: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: sudo apt-get update && sudo apt-get install -y fluid-soundfont-gm
      - run: pip install python-rtmidi
      - run: pip install soundfile
      - run: pip install torch --no-cache-dir --index-url https://download.pytorch.org/whl/cpu
      - name: Install test dependencies
        run: pip install -e .[test] -r requirements-test.txt
      - name: build cyext
        if: matrix.env.CYTHON == '1'
        run: MCY_USE_CYTHON=1 python setup.py build_ext --inplace
      - name: make loops
        run: |
          python - <<'PY'
          import pretty_midi, os
          os.makedirs('mini_loops', exist_ok=True)
          for i in range(2):
              pm = pretty_midi.PrettyMIDI(initial_tempo=120)
              inst = pretty_midi.Instrument(program=0, is_drum=True)
              inst.notes.append(pretty_midi.Note(velocity=100, pitch=36, start=0.0, end=0.1))
              pm.instruments.append(inst)
              pm.write(f'mini_loops/{i}.mid')
          PY
      - run: timeout 180 modcompose groove train mini_loops --order 2
      - run: pytest tests/test_velocity_histogram.py tests/test_timing_corrector.py -q
