name: plugin
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build plugin
        run: |
          if command -v juce-cli >/dev/null; then
            cd plugin
            cmake -B build -DCMAKE_BUILD_TYPE=Release
            cmake --build build --config Release
            cmake --build build --target check || true
          else
            echo "⚠ juce-cli not found; skipping plugin build"
          fi

