name: release
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip/wheels/**/cyext*
          key: ${{ runner.os }}-cyext-${{ hashFiles('cyext/**.pyx') }}
      - uses: conda-incubator/setup-miniconda@v3
      - name: Install dependencies
        run: |
          for i in 1 2 3; do
            pip install -e .[test] -r requirements-test.txt && break || sleep 5
          done
          for i in 1 2 3; do
            pip install build twine mkdocs mkdocs-material mkdocstrings[python] && break || sleep 5
          done
      - run: conda install -y conda-build
        shell: bash -l {0}
      - run: python -m build
        shell: bash -l {0}
      - run: conda activate base && conda-build recipe/ --output-folder conda-artifacts
        shell: bash -l {0}
      - run: twine upload dist/* -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }}
      - run: anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload conda-artifacts/noarch/*.tar.bz2 --user harusan
      - run: mkdocs gh-deploy --force
      - uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/plugin/*
      - name: Generate Changelog
        run: git-chglog --next-tag ${{ github.ref_name }} > CHANGELOG.md
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          body_path: CHANGELOG.md

  tag-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - uses: actions/checkout@v4
      - id: version
        run: echo "VERSION=$(python -c 'import modular_composer as m; print(m.__version__)')" >> $GITHUB_OUTPUT
      - id: check
        run: |
          if git tag --list "v${{ steps.version.outputs.VERSION }}" | grep -q .; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
      - uses: softprops/action-gh-release@v2
        if: steps.check.outputs.skip != 'true'
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          draft: true
